
const DATA_URL='data/sov-baza.json';
const DRAWINGS_DRIVE_FOLDER_ID='1vCPsPaznDOgwRMU_XVDiI4aUhu0o8yFB';
const DRAWINGS_KEY='sov_drawings_index_v2';
const TK25_WMS_URL='https://geoportal.dgu.hr/services/tk/wms';
const TK25_WMS_LAYER='TK25';
const DOF_WMS_URL='https://geoportal.dgu.hr/services/geoportal/ows';
const DOF_WMS_LAYER='DOF';
const GEO_WMS_URL='https://geoportal.dgu.hr/wms';
const GEO_WMS_LAYER='HOK';
let all=[],visible=[],activeFilter='all',markersVisible=true,selectedObjects=new Set();
let SPELEO_CAN_EDIT=false;
let SPELEO_OVERRIDES={};
let selectMode=false,firstCorner=null,selectedRect=null,selectedBounds=null;
const cornerLayer=L.layerGroup();
const map=L.map('map',{zoomControl:true,preferCanvas:true}).setView([44.86,15.45],7);
const blank=L.tileLayer('',{attribution:''}).addTo(map);
const osm=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'OSM'});
const tk25=L.tileLayer.wms(TK25_WMS_URL,{layers:TK25_WMS_LAYER,format:'image/png',transparent:false,version:'1.1.1',srs:'EPSG:3857',attribution:'DGU TK25',detectRetina:false});
const dof=L.tileLayer.wms(DOF_WMS_URL,{layers:DOF_WMS_LAYER,format:'image/png',transparent:false,version:'1.1.1',srs:'EPSG:3857',attribution:'DGU DOF',detectRetina:false});
const geo=L.tileLayer.wms(GEO_WMS_URL,{layers:GEO_WMS_LAYER,styles:'raster',format:'image/png',transparent:false,version:'1.1.1',srs:'EPSG:3857',attribution:'DGU Geo karta / HOK',detectRetina:false});
tk25.addTo(map);
const markerLayer=L.layerGroup().addTo(map);cornerLayer.addTo(map);
let tkOk=0,tkErr=0;tk25.on('tileload',()=>{tkOk++;statusTk()});tk25.on('tileerror',()=>{tkErr++;statusTk()});
L.control.layers({'DGU TK25':tk25,'DGU DOF ortofoto':dof,'DGU Geo karta / HOK':geo,'OSM fallback':osm},{'SOV markeri':markerLayer,'Map download područje':cornerLayer},{collapsed:false}).addTo(map);
function statusTk(){const el=document.getElementById('tk25Status');if(tkErr>4&&tkOk===0){el.className='mapPill bad';el.textContent='TK25 ne vraća tileove — provjeri layer/endpoint'}else if(tkOk>0){el.className='mapPill good';el.textContent='TK25 aktivan · DGU WMS'}else{el.textContent='TK25: učitavanje...'}}
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function statusType(o){const st=norm([o.cadastre_status,o.record_status,o.workflow_raw].join(' '));if(o.in_cadastre_bool===true || st.includes('u_katastru')) return 'green';if(st.includes('nije_u_katastru') || st.includes('za_unos_u_katastar')) return 'red';return 'grey'}
function color(o){return statusType(o)==='green'?'#36e879':statusType(o)==='red'?'#ff5f5f':'#a4adb0'}
function statusLabel(o){return statusType(o)==='green'?'U katastru':statusType(o)==='red'?'Nije u katastru':'Na provjeri / između'}
function setFilter(f){activeFilter=f;document.querySelectorAll('.chip[data-filter]').forEach(c=>c.classList.toggle('active',c.dataset.filter===f));render()}
function matches(o,q){const hay=norm([o.name,o.nearest_place,o.locality,o.municipality,o.county,o.cadastral_number,o.record_status,o.object_type_final,o.note].join(' '));return !q || hay.includes(q)}
function filterObj(o){const type=norm(o.object_type_final||o.name);if(activeFilter==='jama')return type.includes('jama');if(activeFilter==='spilja')return type.includes('spilja')||type.includes('pecina');if(activeFilter==='katastar')return statusType(o)==='green';if(activeFilter==='nije')return statusType(o)==='red';if(activeFilter==='sivo')return statusType(o)==='grey';if(activeFilter==='duboko')return Number(o.depth_m)>=50;if(activeFilter==='perspektiva')return !!o.research_perspective;return true}
function render(){const q=norm(document.getElementById('q').value);visible=all.filter(o=>matches(o,q)&&filterObj(o));document.getElementById('shown').textContent=visible.length;document.getElementById('selectedStat').textContent=selectedObjects.size;drawMarkers();drawResults()}
function drawMarkers(){markerLayer.clearLayers();if(!markersVisible){document.getElementById('marked').textContent=0;return}visible.slice(0,2500).forEach(o=>{const m=L.circleMarker([o.lat,o.lon],{radius:selectedObjects.has(o.id)?10:7.5,color:'#071013',weight:2.5,fillColor:color(o),fillOpacity:.96,className:'markerPulse'}).bindPopup(popupHtml(o),{maxWidth:360}).on('click',()=>showDetails(o,true));m.addTo(markerLayer)});document.getElementById('marked').textContent=Math.min(visible.length,2500)}
function popupHtml(o){return '<div class="objectPopup"><h3>'+esc(o.name)+'</h3><div class="pstatus" style="color:'+color(o)+'">● '+statusLabel(o)+'</div><div class="pmeta"><b>'+esc(o.object_type_final||'Objekt')+'</b><br>'+esc([o.nearest_place,o.municipality,o.county].filter(Boolean).join(' · ')||'—')+'<br>Koordinate: '+fmt(o.lat)+', '+fmt(o.lon)+'<br>Dubina: '+plain(o.depth_m,'m')+' · Duljina: '+plain(o.length_m,'m')+'<br>Katastar: '+esc(o.cadastral_number||'—')+'</div><div class="pdesc">'+esc(o.technical_description||o.access_description||o.note||'Nema dodatnog opisa u JSON bazi.')+'</div><a class="plink" onclick="window.sovOpenObject('+Number(o.id)+')">Otvori full podatke</a></div>'}
function drawResults(){const box=document.getElementById('results');box.innerHTML='';visible.slice(0,120).forEach(o=>{const d=document.createElement('div');d.className='result';d.innerHTML='<small><span class="statusDot" style="background:'+color(o)+'"></span>'+statusLabel(o)+' · '+esc(o.object_type_final||o.record_status||'objekt')+'</small><b>'+esc(o.name)+'</b><div class="meta">'+esc([o.nearest_place,o.municipality,o.county].filter(Boolean).join(' · '))+'<br>Dubina: '+plain(o.depth_m,'m')+' · Duljina: '+plain(o.length_m,'m')+'</div>';d.onclick=()=>{openObject(o)};box.appendChild(d)});if(visible.length>120){const p=document.createElement('p');p.className='muted';p.textContent='Prikazano prvih 120 rezultata. Suzite pretragu za brži rad karte.';box.appendChild(p)}}
function openObject(o){map.setView([o.lat,o.lon],14);showDetails(o,true)}
window.sovOpenObject=function(id){const o=all.find(x=>Number(x.id)===Number(id));if(o)showDetails(o,false)}
function showDetails(o,openPopup){selectedObjects.add(o.id);document.getElementById('selectedStat').textContent=selectedObjects.size;const editBtn=SPELEO_CAN_EDIT?'<button class="btn warn" onclick="openSpeleoEdit('+Number(o.id)+')">Uredi objekt</button>':'';document.getElementById('details').innerHTML='<h2>'+esc(o.name)+'</h2><p class="muted"><span class="statusDot" style="background:'+color(o)+'"></span>'+statusLabel(o)+' · '+esc([o.object_type_final,o.record_status,o.cadastral_number].filter(Boolean).join(' · '))+'</p><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn primary" onclick="exportOneKml('+Number(o.id)+')">KML objekt</button><button class="btn" onclick="copyCoords('+Number(o.id)+')">Kopiraj koordinate</button>'+editBtn+'</div><div class="kv"><div>Koordinate</div><div>'+fmt(o.lat)+', '+fmt(o.lon)+'</div><div>Županija</div><div>'+esc(o.county||'—')+'</div><div>Mjesto</div><div>'+esc([o.nearest_place,o.locality,o.municipality].filter(Boolean).join(' · ')||'—')+'</div><div>Dubina</div><div>'+plain(o.depth_m,'m')+'</div><div>Duljina</div><div>'+plain(o.length_m,'m')+'</div><div>Katastar</div><div>'+esc(o.cadastral_number||'—')+'</div><div>Pristup</div><div>'+esc(o.access_description||'—')+'</div><div>Opis</div><div>'+esc(o.technical_description||'—')+'</div><div>Napomena</div><div>'+esc(o.note||'—')+'</div></div><div id="archiveEditMount"></div>'+renderDrawingsPanel(o);drawMarkers();if(openPopup){setTimeout(()=>{markerLayer.eachLayer(m=>{const ll=m.getLatLng&&m.getLatLng();if(ll&&Math.abs(ll.lat-o.lat)<1e-9&&Math.abs(ll.lng-o.lon)<1e-9)m.openPopup()})},80)}}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function fmt(n){return Number(n).toFixed(6)}function plain(v,s){return v==null||v===''?'—':esc(v)+' '+s}
function setBase(b){if(b==='tk25'){if(map.hasLayer(osm))map.removeLayer(osm);if(!map.hasLayer(tk25))tk25.addTo(map)}else{if(map.hasLayer(tk25))map.removeLayer(tk25);if(!map.hasLayer(osm))osm.addTo(map)}}
function fitAll(){const pts=visible.slice(0,2500).map(o=>[o.lat,o.lon]);if(pts.length)map.fitBounds(pts,{padding:[40,40]})}function toggleMarkers(){markersVisible=!markersVisible;drawMarkers()}

function cleanNameForMatch(v){return norm(String(v||'')).replace(/\.[a-z0-9]{2,5}$/,'').replace(/[_\-\.]+/g,' ').replace(/\b(nacrt|nacrti|scan|sken|topodroid|survey|plan|profile|profil|tlocrt|presjek|jamski|spiljski|jama|spilja|pecina|objekt|final|copy|kopija)\b/g,' ').replace(/\b\d{1,4}\b/g,' ').replace(/\s+/g,' ').trim()}
function loadDrawings(){try{return JSON.parse(localStorage.getItem(DRAWINGS_KEY)||'[]')}catch(e){return[]}}
function saveDrawings(arr){const byKey=new Map();(arr||[]).forEach(d=>{const key=String(d.drive_file_id||d.name||'')+'|'+String(d.object_id||'');if(key.trim())byKey.set(key,d)});localStorage.setItem(DRAWINGS_KEY,JSON.stringify([...byKey.values()]));updateDrawingStatus()}
function updateDrawingStatus(){const n=loadDrawings().length;const el=document.getElementById('drawingImportStatus');if(el)el.textContent=n?('Indeksirano nacrta/TopoDroid fileova: '+n+'. Klikni objekt za prikaz povezanih nacrta.'): 'Nacrti još nisu syncani u ovom browseru.'}
function scoreDrawingMatch(o,fileName){const on=cleanNameForMatch(o.name);const fn=cleanNameForMatch(fileName);if(!on||!fn)return 0;if(fn===on)return 100;if(fn.includes(on)||on.includes(fn))return 92;const aliases=[o.name,o.alternative_name,o.cadastral_number,o.nearest_place].filter(Boolean).map(cleanNameForMatch).filter(Boolean);for(const a of aliases){if(a&&fn.includes(a))return 88}const parts=on.split(' ').filter(x=>x.length>2);let hits=0;parts.forEach(x=>{if(fn.includes(x))hits++});return hits?Math.round(45+hits/Math.max(parts.length,1)*43):0}
function bestObjectForDrawing(fileName){let best=null,bestScore=0;for(const o of all){const sc=scoreDrawingMatch(o,fileName);if(sc>bestScore){best=o;bestScore=sc}}return best&&bestScore>=55?{object:best,score:bestScore}:null}
function drawingsForObject(o){return loadDrawings().map(d=>({...d,score:d.object_id&&String(d.object_id)===String(o.id)?(d.match_score||100):scoreDrawingMatch(o,d.name||d.drive_file_name)})).filter(d=>(d.object_id&&String(d.object_id)===String(o.id))||d.score>=55).sort((a,b)=>(b.score||0)-(a.score||0))}
function drawingType(name){const n=String(name||'').toLowerCase();if(/\.pdf$/.test(n))return 'PDF nacrt';if(/\.(jpg|jpeg|png|webp|tif|tiff|svg)$/.test(n))return 'Slika/nacrt';if(/\.(th2|th|tro|top|tdr|csx|lox)$/.test(n))return 'TopoDroid';if(/\.(kml|gpx)$/.test(n))return 'Track/GIS';if(/\.zip$/.test(n))return 'Arhiva';return 'File'}
function renderDrawingsPanel(o){const matches=drawingsForObject(o);let html='<div class="drawingsPanel"><h3>Nacrti i TopoDroid</h3><p>Nacrti se syncaju iz službene arhive i automatski povezuju s objektom po imenu/partial matchu. Drive folder link nije prikazan userima.</p><div class="drawActions"><button class="btn primary" onclick="syncDriveDrawings()">Sync nacrte</button><button class="btn" onclick="copyDrawingSearch(\''+escJs(o.name)+'\')">Kopiraj naziv</button></div>';
if(matches.length){html+='<div class="drawingList">'+matches.map(d=>{const nm=d.name||d.drive_file_name||'Nacrt';const actions=(d.url&&!d.hideLink)?'<a class="btn" href="'+escAttr(d.url)+'" target="_blank" rel="noopener">Prikaži</a>':'';return '<div class="drawingItem"><b>'+esc(nm)+'</b><small>'+drawingType(nm)+' · match '+(d.match_score||d.score||'—')+'% · '+esc(d.size||d.file_size||'')+'</small><div class="miniActions">'+actions+'</div></div>'}).join('')+'</div>'}else{html+='<div class="hintBox">Za ovaj objekt trenutno nema matchanog nacrta. Klikni “Sync nacrte” da app povuče indeks iz arhive.</div>'}
return html+'</div>'}
function copyDrawingSearch(name){navigator.clipboard&&navigator.clipboard.writeText(name)}
function exportDrawingsIndex(){downloadBlob(JSON.stringify(loadDrawings(),null,2),'sov-nacrti-topodroid-index.json','application/json')}
function clearLocalDrawings(){if(confirm('Obrisati lokalni index nacrta u ovom browseru?')){saveDrawings([]);render()}}
function setupDrawingUpload(){const input=document.getElementById('drawingUpload');if(!input)return;input.addEventListener('change',()=>{const existing=loadDrawings();const add=[...input.files].map(f=>{const best=bestObjectForDrawing(f.name);return {name:f.name,size:Math.round(f.size/1024)+' KB',type:f.type||drawingType(f.name),url:URL.createObjectURL(f),local:true,hideLink:false,object_id:best&&best.object?String(best.object.id):null,match_score:best?best.score:0,addedAt:new Date().toISOString()}});saveDrawings(existing.concat(add));input.value='';render();});updateDrawingStatus()}
async function hydrateDrawingsFromSupabase(){try{const sb=window.SOVAuth&&SOVAuth.getClient&&SOVAuth.getClient();if(!sb)return;const res=await sb.from('speleo_object_drawings').select('object_id,drive_file_id,drive_file_name,mime_type,file_size,match_score,match_status,metadata,synced_at').limit(5000);if(res.error)throw res.error;const rows=(res.data||[]).map(r=>({object_id:String(r.object_id||''),drive_file_id:r.drive_file_id,name:r.drive_file_name,mime_type:r.mime_type,size:r.file_size,match_score:r.match_score,match_status:r.match_status,hideLink:true,source:'supabase',synced_at:r.synced_at,metadata:r.metadata||{}}));if(rows.length)saveDrawings(loadDrawings().concat(rows));}catch(e){console.warn('drawing hydrate skipped',e)}}
async function fetchDriveDrawingFiles(){const endpoint=window.SOV_DRAWINGS_SYNC_ENDPOINT||'';if(endpoint){const r=await fetch(endpoint,{cache:'no-store'});if(!r.ok)throw new Error('Sync endpoint HTTP '+r.status);const j=await r.json();return Array.isArray(j)?j:(j.files||[])}const key=window.SOV_GOOGLE_DRIVE_API_KEY||'';if(key){let files=[],pageToken='';do{const q=encodeURIComponent("'"+DRAWINGS_DRIVE_FOLDER_ID+"' in parents and trashed=false");const url='https://www.googleapis.com/drive/v3/files?q='+q+'&fields=nextPageToken,files(id,name,mimeType,size,webViewLink,modifiedTime)&pageSize=1000&key='+encodeURIComponent(key)+(pageToken?'&pageToken='+encodeURIComponent(pageToken):'');const r=await fetch(url);if(!r.ok)throw new Error('Google Drive API HTTP '+r.status);const j=await r.json();files=files.concat(j.files||[]);pageToken=j.nextPageToken||'';}while(pageToken);return files}
throw new Error('Nije konfiguriran SOV_DRAWINGS_SYNC_ENDPOINT ili SOV_GOOGLE_DRIVE_API_KEY u assets/supabase-config.js')}
async function syncDriveDrawings(){const status=document.getElementById('drawingImportStatus');try{if(status)status.textContent='Sync nacrta kreće...';const files=await fetchDriveDrawingFiles();const accepted=files.filter(f=>/\.(pdf|jpg|jpeg|png|webp|tif|tiff|svg|th2|th|tro|top|tdr|csx|lox|zip|kml|gpx)$/i.test(f.name||''));const matched=[];for(const f of accepted){const best=bestObjectForDrawing(f.name);if(!best)continue;matched.push({object_id:String(best.object.id),drive_file_id:String(f.id||f.drive_file_id||f.name),name:f.name||f.drive_file_name,mime_type:f.mimeType||f.mime_type||'',size:f.size?Math.round(Number(f.size)/1024)+' KB':'',match_score:best.score,match_status:best.score>=90?'auto_matched':'partial_match',hideLink:true,source:'drive_sync',synced_at:new Date().toISOString(),metadata:{modifiedTime:f.modifiedTime||null}})}saveDrawings(loadDrawings().concat(matched));const sb=window.SOVAuth&&SOVAuth.getClient&&SOVAuth.getClient();if(sb&&matched.length){const u=window.SOVAuth.currentUser?await SOVAuth.currentUser():null;const rows=matched.map(d=>({object_id:d.object_id,drive_file_id:d.drive_file_id,drive_file_name:d.name,mime_type:d.mime_type,file_size:d.size,match_score:d.match_score,match_status:d.match_status,synced_by:u&&u.id||null,metadata:d.metadata||{}}));const res=await sb.from('speleo_object_drawings').upsert(rows,{onConflict:'drive_file_id'});if(res.error)throw res.error;}if(status)status.textContent='Sync gotovo: '+matched.length+' nacrta povezano s objektima. '+(accepted.length-matched.length)+' fileova treba ručnu provjeru.';render();}catch(e){console.error(e);if(status)status.textContent='Greška synca nacrta: '+(e.message||e);alert('Greška synca nacrta: '+(e.message||e));}}
function openSpeleoEdit(id){if(!SPELEO_CAN_EDIT)return alert('Uređivanje vidi samo admin/arhivar.');const o=all.find(x=>String(x.id)===String(id));if(!o)return;const m=document.getElementById('archiveEditMount');m.innerHTML=`<form class="archiveEdit" onsubmit="saveSpeleoEdit(event,${Number(o.id)})"><h3>Uredi objekt</h3><div class="archiveGrid"><label>Naziv<input name="name" value="${escAttr(o.name||'')}"></label><label>Tip<input name="object_type_final" value="${escAttr(o.object_type_final||'')}"></label><label>Najbliže mjesto<input name="nearest_place" value="${escAttr(o.nearest_place||'')}"></label><label>Općina/grad<input name="municipality" value="${escAttr(o.municipality||'')}"></label><label>Županija<input name="county" value="${escAttr(o.county||'')}"></label><label>Katastarski broj<input name="cadastral_number" value="${escAttr(o.cadastral_number||'')}"></label><label>Lat<input name="lat" value="${escAttr(o.lat||'')}"></label><label>Lon<input name="lon" value="${escAttr(o.lon||'')}"></label><label>Dubina m<input name="depth_m" value="${escAttr(o.depth_m||'')}"></label><label>Duljina m<input name="length_m" value="${escAttr(o.length_m||'')}"></label><label class="archiveWide">Status / provjera<input name="record_status" value="${escAttr(o.record_status||'')}"></label><label class="archiveWide">Pristup<textarea name="access_description">${esc(o.access_description||'')}</textarea></label><label class="archiveWide">Opis<textarea name="technical_description">${esc(o.technical_description||'')}</textarea></label><label class="archiveWide">Napomena<textarea name="note">${esc(o.note||'')}</textarea></label></div><div class="archiveActions"><button class="btn primary" type="submit">Spremi u bazu</button><button class="btn" type="button" onclick="showDetails(all.find(x=>String(x.id)==='${String(o.id)}'),false)">Odustani</button></div><p class="muted">Arhivar mijenja samo ovaj objekt. Hard-delete nije dostupan.</p></form>`;m.scrollIntoView({behavior:'smooth',block:'nearest'});}
async function saveSpeleoEdit(ev,id){ev.preventDefault();const f=new FormData(ev.target);const patch={};for(const [k,v] of f.entries()){let val=String(v).trim();if(['lat','lon','depth_m','length_m'].includes(k)&&val!=='')val=Number(val);patch[k]=val;}const idx=all.findIndex(x=>String(x.id)===String(id));if(idx<0)return;const before={...all[idx]};all[idx]={...all[idx],...patch};const payload={object_id:String(id),data:patch,updated_at:new Date().toISOString()};try{const sb=window.SOVAuth&&SOVAuth.getClient&&SOVAuth.getClient();if(sb){const u=await SOVAuth.currentUser();payload.updated_by=u&&u.id||null;let res=await sb.from('speleo_object_overrides').upsert(payload,{onConflict:'object_id'});if(res.error)throw res.error;await sb.from('speleo_object_edits').insert({object_id:String(id),edited_by:payload.updated_by,old_values:before,new_values:patch,changed_fields:Object.keys(patch),note:patch.note||null}).catch(()=>{});}else{throw new Error('no supabase')}}catch(e){const arr=JSON.parse(localStorage.getItem('sov_speleo_object_overrides')||'[]').filter(r=>String(r.object_id)!==String(id));arr.push(payload);localStorage.setItem('sov_speleo_object_overrides',JSON.stringify(arr));console.warn('saved locally',e);}render();showDetails(all[idx],false);alert('Spremljeno.');}
function selectedOrVisible(){const sel=all.filter(o=>selectedObjects.has(o.id));return sel.length?sel:visible}
function kmlFor(arr){let k='<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>SOV export</name><Style id="u"><IconStyle><color>ff79e836</color><scale>1.15</scale></IconStyle></Style><Style id="n"><IconStyle><color>ff5f5fff</color><scale>1.15</scale></IconStyle></Style><Style id="s"><IconStyle><color>ffb0ada4</color><scale>1.05</scale></IconStyle></Style>';arr.forEach(o=>{const sid=statusType(o)==='green'?'u':statusType(o)==='red'?'n':'s';k+='<Placemark><name>'+esc(o.name)+'</name><styleUrl>#'+sid+'</styleUrl><description>'+esc([statusLabel(o),o.record_status,o.object_type_final,o.cadastral_number,o.nearest_place].filter(Boolean).join(' | '))+'</description><Point><coordinates>'+o.lon+','+o.lat+',0</coordinates></Point></Placemark>'});return k+'</Document></kml>'}
function exportVisibleKml(){downloadBlob(kmlFor(selectedOrVisible()),'sov-objects.kml','application/vnd.google-earth.kml+xml')}function exportOneKml(id){const o=all.find(x=>x.id===id);if(o)downloadBlob(kmlFor([o]),'sov-'+safeName(o.name)+'.kml','application/vnd.google-earth.kml+xml')}
function exportVisibleGeoJson(){const arr=selectedOrVisible();const gj={type:'FeatureCollection',features:arr.map(o=>({type:'Feature',properties:{id:o.id,name:o.name,status:statusLabel(o),type:o.object_type_final,depth_m:o.depth_m,length_m:o.length_m,cadastre:o.cadastral_number},geometry:{type:'Point',coordinates:[o.lon,o.lat]}}))};downloadBlob(JSON.stringify(gj,null,2),'sov-objects.geojson','application/geo+json')}
function exportVisibleCsv(){const arr=selectedOrVisible();const rows=[['id','name','status','type','lat','lon','depth_m','length_m','county','municipality','nearest_place','cadastre'].join(',')].concat(arr.map(o=>[o.id,o.name,statusLabel(o),o.object_type_final,o.lat,o.lon,o.depth_m,o.length_m,o.county,o.municipality,o.nearest_place,o.cadastral_number].map(csv).join(',')));downloadBlob(rows.join('\n'),'sov-objects.csv','text/csv;charset=utf-8')}function csv(v){return '"'+String(v??'').replace(/"/g,'""')+'"'}function safeName(s){return norm(s).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'objekt'}
function copyCoords(id){const o=all.find(x=>x.id===id);if(o)navigator.clipboard?.writeText(fmt(o.lat)+', '+fmt(o.lon))}
function startSelectArea(){selectMode=true;firstCorner=null;if(selectedRect){selectedRect.remove();selectedRect=null}cornerLayer.clearLayers();selectedBounds=null;document.getElementById('selectionHint').textContent='1/2 Klikni prvi kut Map download područja';document.getElementById('selectionHint').classList.add('show');document.getElementById('bboxText').textContent='1/2: klikni prvi kut Map download područja na karti.';document.getElementById('tileCount').textContent='Čekam prvi kut Map download područja.';map.getContainer().style.cursor='crosshair'}
map.on('click',e=>{if(!selectMode)return;if(!firstCorner){firstCorner=e.latlng;cornerLayer.clearLayers();L.marker(firstCorner,{icon:cornerIcon()}).addTo(cornerLayer);document.getElementById('selectionHint').textContent='2/2 Klikni suprotni kut područja';document.getElementById('bboxText').textContent='2/2: klikni suprotni kut Map download područja.';return}selectedBounds=L.latLngBounds(firstCorner,e.latlng);if(selectedRect)selectedRect.remove();selectedRect=L.rectangle(selectedBounds,{color:'#d7f66f',weight:6,fill:true,fillColor:'#d7f66f',fillOpacity:.18,dashArray:'14 8'}).addTo(map);cornerLayer.clearLayers();L.marker(selectedBounds.getSouthWest(),{icon:cornerIcon()}).addTo(cornerLayer);L.marker(selectedBounds.getNorthEast(),{icon:cornerIcon()}).addTo(cornerLayer);selectMode=false;map.getContainer().style.cursor='';document.getElementById('selectionHint').classList.remove('show');updateBboxText();map.fitBounds(selectedBounds,{padding:[70,70]})});
function cornerIcon(){return L.divIcon({className:'',html:'<div class="areaCorner"></div>',iconSize:[20,20],iconAnchor:[10,10]})}function updateBboxText(){if(!selectedBounds)return;const b=selectedBounds;document.getElementById('bboxText').innerHTML='Odabrano: W '+b.getWest().toFixed(5)+' / S '+b.getSouth().toFixed(5)+' / E '+b.getEast().toFixed(5)+' / N '+b.getNorth().toFixed(5);document.getElementById('tileCount').textContent='Procjena: '+estimateTiles()+' tileova. Klikni Skini mapu (.mbtiles).'}
function lon2tile(lon,z){return Math.floor((lon+180)/360*Math.pow(2,z))}function lat2tile(lat,z){const r=lat*Math.PI/180;return Math.floor((1-Math.log(Math.tan(r)+1/Math.cos(r))/Math.PI)/2*Math.pow(2,z))}function rad2deg(r){return r*180/Math.PI}function mercLon(lon){return lon*20037508.34/180}function mercLat(lat){lat=Math.max(Math.min(lat,85.05112878),-85.05112878);return Math.log(Math.tan((90+lat)*Math.PI/360))/(Math.PI/180)*20037508.34/180}function tileBbox3857(x,y,z){const n=Math.pow(2,z),lon1=x/n*360-180,lon2=(x+1)/n*360-180,lat1=rad2deg(Math.atan(Math.sinh(Math.PI*(1-2*y/n)))),lat2=rad2deg(Math.atan(Math.sinh(Math.PI*(1-2*(y+1)/n))));return [mercLon(lon1),mercLat(lat2),mercLon(lon2),mercLat(lat1)].join(',')}
function tilesForSelection(){if(!selectedBounds)throw new Error('Nema područja.');let zmin=+document.getElementById('zmin').value,zmax=+document.getElementById('zmax').value;if(zmax<zmin)[zmin,zmax]=[zmax,zmin];const b=selectedBounds;let arr=[];for(let z=zmin;z<=zmax;z++){let x1=lon2tile(b.getWest(),z),x2=lon2tile(b.getEast(),z),y1=lat2tile(b.getNorth(),z),y2=lat2tile(b.getSouth(),z);for(let x=x1;x<=x2;x++)for(let y=y1;y<=y2;y++)arr.push({z,x,y})}return arr}function estimateTiles(){try{return tilesForSelection().length}catch(e){return 0}}
function wmsTileUrl(t){return TK25_WMS_URL+'?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&LAYERS='+encodeURIComponent(TK25_WMS_LAYER)+'&STYLES=&FORMAT=image/png&TRANSPARENT=false&SRS=EPSG:3857&BBOX='+tileBbox3857(t.x,t.y,t.z)+'&WIDTH=256&HEIGHT=256'}
async function downloadMbtiles(){if(!selectedBounds){alert('Prvo označi Map download područje.');return}const tiles=tilesForSelection();if(tiles.length>2000&&!confirm('Ovo je '+tiles.length+' tileova i može trajati. Nastaviti?'))return;const SQL=await initSqlJs({locateFile:f=>'https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.10.3/'+f});const db=new SQL.Database();db.run('CREATE TABLE metadata (name text, value text);CREATE TABLE tiles (zoom_level integer, tile_column integer, tile_row integer, tile_data blob);CREATE UNIQUE INDEX tile_index on tiles (zoom_level, tile_column, tile_row);');db.run('INSERT INTO metadata VALUES (?,?),(?,?),(?,?),(?,?)',['name','SOV TK25 offline','type','baselayer','format','png','bounds',[selectedBounds.getWest(),selectedBounds.getSouth(),selectedBounds.getEast(),selectedBounds.getNorth()].join(',')]);const stmt=db.prepare('INSERT OR REPLACE INTO tiles VALUES (?,?,?,?)');let done=0,ok=0;for(const t of tiles){try{const r=await fetch(wmsTileUrl(t),{mode:'cors'});if(!r.ok)throw new Error(r.status);const buf=new Uint8Array(await r.arrayBuffer());stmt.run([t.z,t.x,Math.pow(2,t.z)-1-t.y,buf]);ok++}catch(e){console.warn('Tile failed',t,e)}done++;document.getElementById('bar').style.width=(done/tiles.length*100)+'%';document.getElementById('tileCount').textContent='Map download: '+done+' / '+tiles.length+' · uspješno '+ok}stmt.free();downloadBlob(db.export(),'sov-tk25-offline.mbtiles','application/octet-stream');document.getElementById('tileCount').textContent='Gotovo: skinut je sov-tk25-offline.mbtiles ('+ok+' tileova).'}
function downloadBlob(data,name,type){const blob=new Blob([data],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
fetch(DATA_URL).then(r=>r.json()).then(async d=>{all=d.filter(o=>Number.isFinite(o.lat)&&Number.isFinite(o.lon));await initArchiveRole();applyObjectOverrides(await loadSpeleoOverrides());await hydrateDrawingsFromSupabase();document.getElementById('total').textContent=all.length;const params=new URLSearchParams(location.search);const oid=params.get('object')||params.get('id');const q=params.get('q');if(q){document.getElementById('q').value=q}setupDrawingUpload();render();if(oid){const obj=all.find(o=>String(o.id)===String(oid));if(obj){openObject(obj);map.setView([obj.lat,obj.lon],15)}}else{fitAll()}}).catch((e)=>{console.error(e);document.getElementById('results').innerHTML='<p class="muted">Ne mogu učitati data/sov-baza.json.</p>'});
