package com.darko.speleov1

import androidx.compose.runtime.compositionLocalOf

enum class AppLanguage { HR, EN }

val LocalAppLanguage = compositionLocalOf { AppLanguage.HR }

fun appText(hr: String, en: String, language: AppLanguage): String = if (language == AppLanguage.EN) en else hr

fun AppLanguage.pick(hr: String, en: String): String = appText(hr, en, this)

fun localizedStaticLabel(value: String, language: AppLanguage): String {
    if (language == AppLanguage.HR) return value
    enStaticLabels[value]?.let { return it }
    return translateDynamicLabel(value)
}

private val enStaticLabels = mapOf(
    "Pretraga" to "Search",
    "Karta" to "Map",
    "Izleti" to "Trips",
    "Tools" to "Tools",
    "Alati" to "Tools",
    "Overlay" to "Layers",
    "Slojevi" to "Layers",
    "Settings" to "Settings",
    "Postavke" to "Settings",
    "Kalkulator koordinata" to "Coordinate calculator",
    "Speleo zapisnik" to "Field log",
    "Kalendar izleta / akcija" to "Trip / action calendar",
    "Plati članarinu" to "Pay membership",
    "Upute" to "Read me",
    "Read me" to "Read me",
    "About" to "About",
    "O aplikaciji" to "About",
    "Provjeravam…" to "Checking…",
    "Provjeri ažuriranje" to "Check for update",
    "Dodatni alati i prečaci" to "Extra tools and shortcuts",
    "GPS Field Status" to "GPS Field Status",
    "GPS stanje na terenu" to "GPS Field Status",
    "GPS i signal" to "GPS and signal",
    "GPS status" to "GPS status",
    "SAT U FIXU" to "SAT IN FIX",
    "Live update" to "Live update",
    "zadnji fix" to "last fix",
    "PRECIZNOST" to "ACCURACY",
    "VISINA" to "ALTITUDE",
    "SMJER" to "HEADING",
    "BRZINA" to "SPEED",
    "Kompas" to "Compass",
    "Terenski savjet" to "Field tip",
    "Pretraži" to "Search",
    "Rezultati pretrage" to "Search results",
    "Počni s pretragom →" to "Start searching →",
    "Upiši naziv, lokaciju ili pločicu." to "Enter name, place or tile.",
    "Još nema rezultata za prikaz." to "No results to show yet.",
    "Očisti sve filtere" to "Clear all filters",
    "Dodaj filtere" to "Add filters",
    "Boja + kvačica = filter je ON" to "Color + checkmark = filter is ON",
    "SOV" to "SOV",
    "Sve" to "All",
    "Jama" to "Pit",
    "Špilja" to "Cave",
    "Jame" to "Pits",
    "Špilje" to "Caves",
    "Dubina" to "Depth",
    "Opis" to "Description",
    "Opis (opcionalno)" to "Description (optional)",
    "Lokacija" to "Location",
    "Najbliže mjesto" to "Nearest place",
    "Najbliže oko mene" to "Nearest around me",
    "Čekam lokaciju." to "Waiting for location.",
    "Nema dozvole za lokaciju" to "No location permission",
    "Otvori na karti" to "Open on map",
    "Prikaži na karti" to "Show on map",
    "Otvori" to "Open",
    "Open" to "Open",
    "Open in Google Maps" to "Open in Google Maps",
    "Otvori original" to "Open original",
    "Otvori vanjskim preglednikom" to "Open with external viewer",
    "Otvori postavke" to "Open settings",
    "Spremi" to "Save",
    "Spremi izmjene" to "Save changes",
    "Odustani" to "Cancel",
    "Obriši" to "Delete",
    "Potvrdi" to "Confirm",
    "OK" to "OK",
    "Natrag" to "Back",
    "Kasnije" to "Later",
    "Prekini" to "Stop",
    "Podijeli" to "Share",
    "Podaci" to "Data",
    "Akcije" to "Actions",
    "Favorit" to "Favorite",
    "Detaljno" to "Details",
    "Osnovno" to "Basic",
    "Osvježi" to "Refresh",
    "Osvježi index" to "Refresh index",
    "Promijeni URL" to "Change URL",
    "URL" to "URL",
    "Očisti URL" to "Clear URL",
    "Preuzmi" to "Download",
    "Preuzmi KML" to "Download KML",
    "Export KML" to "Export KML",
    "Export GPX" to "Export GPX",
    "Export koordinata" to "Export coordinates",
    "Export arhive" to "Export archive",
    "Download moje custom KML točke" to "Download my custom KML points",
    "KML" to "KML",
    "KML možeš otvoriti u kartama/GIS-u." to "Open KML in maps/GIS.",
    "Odaberi izvoz." to "Choose export.",
    "Karta i slojevi" to "Maps & Layers",
    "Maps & overlays" to "Maps & Layers",
    "Osnovna karta" to "Base map",
    "Import karte" to "Import map",
    "Import karte / layera" to "Import map / layer",
    "Import završen" to "Import finished",
    "Karta nije odabrana" to "No map selected",
    "Karta je trenutno prazna" to "The map is currently empty",
    "Alati karte" to "Map tools",
    "Brze akcije za teren" to "Quick field actions",
    "Karta i područje" to "Map and area",
    "Odaberi kartu i slojeve." to "Choose map and layers.",
    "Odaberi kategorije." to "Choose categories.",
    "FIELD LAYERS" to "FIELD LAYERS",
    "FIELD CONTROL" to "FIELD CONTROL",
    "Layer / LAYERS" to "Layer / LAYERS",
    "Redoslijed: karta → slojevi → objekti → trackovi." to "Order: map → layers → objects → tracks.",
    "Sloj će biti vidljiv svima nakon osvježavanja." to "Visible after refresh.",
    "Nema spremljenih slojeva." to "No saved layers.",
    "Dodaj WMS sloj" to "Add WMS layer",
    "Spremi kao kartu ili sloj." to "Save as map or layer.",
    "Dostupni layeri" to "Available layers",
    "Format" to "Format",
    "CRS/SRS" to "CRS/SRS",
    "CRS iz odabranog layera" to "CRS from selected layer",
    "Naziv u appu" to "Name in app",
    "Ime layera / tracka" to "Layer / track name",
    "Filtriraj po imenu..." to "Filter by name...",
    "Spremi i uključi" to "Save and enable",
    "Nemaš offline karata" to "You have no offline maps",
    "Skini offline područje" to "Download offline area",
    "Izaberi područje na karti" to "Choose an area on the map",
    "Naziv offline karte" to "Offline map name",
    "Lokalno spremljeni terenski paketi" to "Locally saved field packages",
    "Offline zapisnik" to "Offline field log",
    "Online zapisnik" to "Online field log",
    "Radi offline" to "Works offline",
    "Skeniraj folder" to "Scan folder",
    "Download/SOV/Offline" to "Download/SOV/Offline",
    "Moji izleti" to "My trips",
    "Izleti iz zajedničke tablice" to "Trips from shared table",
    "Novi izlet" to "New trip",
    "Spremi izlet" to "Save trip",
    "Naziv izleta / aktivnost" to "Trip / activity name",
    "Datum izleta" to "Trip date",
    "Datum početka" to "Start date",
    "Datum završetka" to "End date",
    "Datum / trajanje" to "Date / duration",
    "Lokacija" to "Location",
    "Opis aktivnosti" to "Activity description",
    "Cilj izleta" to "Trip goal",
    "Način izvođenja aktivnosti" to "Activity type",
    "Grad / regija za vremensku prognozu" to "City / region for weather forecast",
    "Neobavezno." to "Optional.",
    "Paket za teren." to "Field package.",
    "Označi područje na karti." to "Select area on map.",
    "Karta → Tools → Download" to "Map → Tools → Download",
    "Prijava na izlet" to "Trip RSVP",
    "Spremi prijavu" to "Save RSVP",
    "Obriši izlet?" to "Delete trip?",
    "Obriši iz zajedničkog rasporeda" to "Delete from shared schedule",
    "Obriši iz zajedničkog rasporeda?" to "Delete from shared schedule?",
    "Prošli izleti" to "Past trips",
    "MOJ IZLET" to "MY TRIP",
    "Samo pregled." to "View only.",
    "Nema izleta." to "No trips.",
    "Trackovi" to "Tracks",
    "Novi track" to "New track",
    "Spremi track" to "Save track",
    "Spremi zajedničku" to "Save shared",
    "Zajednički" to "Shared",
    "Postojeći track" to "Existing track",
    "Nastavi postojeći" to "Continue existing",
    "Sažetak tracka" to "Track summary",
    "Ime tracka" to "Track name",
    "Ime rute" to "Route name",
    "Dodaj ime i spremi." to "Add name and save.",
    "Već postoji track. Nastaviti ili pokrenuti novi?" to "Track exists. Continue or start new?",
    "Nema trackova" to "No tracks",
    "Nema trackova s imenom" to "No tracks with that name",
    "Snimljeno" to "Recorded",
    "GPS uzoraka" to "GPS samples",
    "Duljina" to "Length",
    "Uspon" to "Ascent",
    "Silazak" to "Descent",
    "Drawing pen s Undo, Save i Cancel" to "Drawing pen with Undo, Save and Cancel",
    "Crtež se sprema kao track." to "Drawing saves as track.",
    "Spremi ručno nacrtanu rutu" to "Save hand-drawn route",
    "Dugi klik = točka/navigacija." to "Long press = point/navigation.",
    "Add waypoint" to "Add waypoint",
    "Ime točke" to "Point name",
    "Kratka bilješka." to "Short note.",
    "GPS točka bit će spremljena." to "GPS point will be saved.",
    "Dodaj waypoint na ovoj lokaciji?\n" to "Add waypoint at this location?\n",
    "Fotografije" to "Photos",
    "Nema fotografija." to "No photos.",
    "Nacrti i TopoDroid" to "Drawings and TopoDroid",
    "Nacrti iz Drivea" to "Drawings from Drive",
    "Dodaj nacrt / export" to "Add drawing / export",
    "Osvježi index" to "Refresh index",
    "Pripremam nacrt…" to "Preparing drawing…",
    "Pregledaj" to "Preview",
    "Preview" to "Preview",
    "Drive" to "Drive",
    "Nacrti: JPG, PNG, TIFF, WEBP, PDF." to "Drawings: JPG, PNG, TIFF, WEBP, PDF.",
    "Nema nacrta." to "No drawings.",
    "Pregled nije dostupan. Original možeš otvoriti." to "Preview unavailable. Open original.",
    "Auto match koristi" to "Auto match uses",
    "GPS Status" to "GPS Status",
    "Signal i pokrivenost" to "Signal and coverage",
    "Osvježi ćelije" to "Refresh cells",
    "Dostupne mreže u okolici" to "Available nearby networks",
    "Prikaz mreže koju mobitel vidi." to "Nearby networks.",
    "Dopusti mrežu" to "Allow network",
    "Baterija" to "Battery",
    "Android može ugasiti GPS u pozadini.\n\n" to "Android may stop GPS in background.\n\n",
    "Nema mjerenja" to "No measurements",
    "Odaberi orijentaciju karte." to "Choose map orientation.",
    "Orijentacija karte" to "Map orientation",
    "Sjever gore" to "North up",
    "Smjer kretanja gore" to "Heading up",
    "GPS gumb uključuje lokaciju." to "GPS button enables location.",
    "Pen" to "Pen",
    "Center" to "Center",
    "Follow" to "Follow",
    "Profil" to "Profile",
    "Rezultat" to "Result",
    "Konvertiraj" to "Convert",
    "Koordinate" to "Coordinates",
    "Dužina (Lon)" to "Longitude (Lon)",
    "HTRS96/TM" to "HTRS96/TM",
    "WGS84" to "WGS84",
    "Pitanja, greške i prijedlozi" to "Questions, bugs and suggestions",
    "Email" to "Email",
    "Dobrodošao u SOV" to "Welcome to SOV",
    "Brze akcije za teren" to "Quick field actions",
    "Postavke" to "Settings",
    "Jezik aplikacije" to "App language",
    "Odaberi jezik." to "Choose language.",
    "Ime" to "Name",
    "Ime igrača" to "Player name",
    "High scoreovi" to "High scores",
    "Speleo Runner high scoreovi" to "Speleo Runner high scores",
    "Metri" to "Meters",
    "šišmiša" to "bats",
    "stanica" to "stations",
    "centerline" to "centerline",
    "Note" to "Note",
    "Druga svrha" to "Other purpose",
    "Plan" to "Plan",
    "Pristup" to "Approach",
    "QC" to "QC",
    "Prioritet" to "Priority",
    "Pločica" to "Tile",
    "Broj pločice na objektu" to "Object tile number",
    "Izmijeni koordinate" to "Edit coordinates",
    "Geolociraj na kartu" to "Geolocate on map",
    "Moja bilješka" to "My note",
    "Napomena" to "Note",
    "Kratki plan, napomena, logistika…" to "Short plan, note, logistics…",
    "Fotografije" to "Photos",
    "Galerija" to "Gallery",
    "Gallery" to "Gallery",
    "Spremi fotografiju" to "Save photo",
    "Nova verzija dostupna" to "New version available",
    "Dostupna verzija" to "Available version",
    "Instalirana verzija" to "Installed version",
    "Skidam APK i pripremam instalaciju…" to "Downloading APK and preparing installation…",
    "Ažurirano" to "Updated",
    "Android nije vratio dodatne mreže na ovoj lokaciji" to "Android did not return additional networks at this location",
    "Automatski iz područja" to "Automatically from area",
    "Ažuriraj" to "Update",
    "CSV" to "CSV",
    "CSV mora sadržavati koordinate" to "CSV must contain coordinates",
    "Custom WMS" to "Custom WMS",
    "DD/MM/GGGG" to "DD/MM/YYYY",
    "Datoteka je učitana, ali nije pronađen nijedan iskoristiv objekt." to "The file loaded, but no usable objects were found.",
    "Dodaj GPX/KML track s mobitela" to "Add GPX/KML track from phone",
    "Dopusti READ_PHONE_STATE za mrežni tip i signal." to "Allow READ_PHONE_STATE for network type and signal.",
    "Dopusti instalaciju iz ovog izvora pa zatim opet klikni Ažuriraj." to "Allow installation from this source, then tap Update again.",
    "Web mapa metri." to "EPSG:3857 meters, common in web maps and tile systems.",
    "Filtri" to "Filters",
    "Filtriraj po stanici (npr. 0, A1...)" to "Filter by station (e.g. 0, A1...)",
    "GPS bearing" to "GPS bearing",
    "GPS centar" to "GPS center",
    "GPS je ugašen. Uključi GPS u postavkama." to "GPS is off. Turn on GPS in settings.",
    "GPS pozicija isključena" to "GPS position off",
    "GPS pozicija nije dostupna" to "GPS position unavailable",
    "GPS smjer" to "GPS heading",
    "Geo sloj" to "Geo layer",
    "Geological Units" to "Geological Units",
    "Geološki sloj" to "Geological layer",
    "Greška pri brisanju — provjeri internet." to "Delete failed — check your internet connection.",
    "Greška pri downloadu ažuriranja." to "Update download failed.",
    "Greška pri exportu" to "Export failed",
    "Greška pri exportu GPX-a" to "GPX export failed",
    "Greška pri exportu točke" to "Point export failed",
    "Greška — provjeri internet." to "Error — check your internet connection.",
    "Točka nije spremljena. Provjeri internet." to "Point not saved. Check internet.",
    "Track nije spremljen. Provjeri internet." to "Track not saved. Check internet.",
    "Import je pročitan, ali nema podržanih geometrija za prikaz" to "The import was read, but it has no supported geometries to display",
    "Isključeno" to "Off",
    "Istraživanje" to "Exploration",
    "Izaberi područje" to "Choose area",
    "Izlet iz rasporeda" to "Scheduled trip",
    "Izvezi" to "Export",
    "Izvezi CSV" to "Export CSV",
    "Izvezi KML" to "Export KML",
    "Izvor" to "Source",
    "Još trebaš odabrati područje na karti." to "You still need to choose an area on the map.",
    "KML točka exportirana" to "KML point exported",
    "KML track exportiran" to "KML track exported",
    "Karta je odabrana." to "Map selected.",
    "Karta spremna" to "Map ready",
    "Kompas stabilan" to "Compass stable",
    "Korak 1/3 — Datum i lokacija (obavezno)" to "Step 1/3 — Date and location (required)",
    "Korak 2/3 — Offline karta i područje" to "Step 2/3 — Offline map and area",
    "Korak 3/3 — Trackovi i završi" to "Step 3/3 — Tracks and finish",
    "Kreiraj svoju bazu" to "Create your own database",
    "Latitude / širina" to "Latitude",
    "Latitude mora biti između -90 i 90." to "Latitude must be between -90 and 90.",
    "Ledeno uže" to "Icy rope",
    "Live GPS tracking isključen" to "Live GPS tracking off",
    "Live GPS tracking uključen" to "Live GPS tracking on",
    "Live tracking radi • tražim GPS fix" to "Live tracking active • looking for GPS fix",
    "Lokacija trenutno nije aktivna" to "Location is not active right now",
    "Longitude / dužina" to "Longitude",
    "Longitude mora biti između -180 i 180." to "Longitude must be between -180 and 180.",
    "Moja baza" to "My Base",
    "Moja baza očišćena" to "My Base cleared",
    "Nastavi" to "Continue",
    "Nastavi →" to "Continue →",
    "Nastavljen postojeći track" to "Continued existing track",
    "Ne mogu pročitati koordinate." to "Cannot read coordinates.",
    "Nema PNG tileova za export." to "No PNG tiles available for export.",
    "Nema budućih izleta u rasporedu" to "No upcoming trips in the schedule",
    "Nema custom KML točaka za export" to "No custom KML points to export",
    "Nema dodatnih mreža za prikaz" to "No additional networks to show",
    "Nema dozvole za čitanje mreže" to "No permission to read network state",
    "Nema objekata za export" to "No objects to export",
    "Nema podržan track" to "No supported track",
    "Nema spremljenih scoreova ili nema interneta." to "No saved scores or no internet.",
    "Nema spremljenih trackova." to "No saved tracks.",
    "Nema točaka u Mojoj bazi" to "No points in My Base",
    "Nema učitanih izleta iz rasporeda" to "No trips loaded from the schedule",
    "Nepoznata mreža" to "Unknown network",
    "Obriši sloj" to "Delete layer",
    "Označi područje i spremi." to "Select area and save.",
    "Odspoji" to "Unlink",
    "Offline karta je spremljena. Vraćam te u flow izleta." to "Offline map saved. Returning to the trip flow.",
    "Otvaram područje izleta" to "Opening trip area",
    "Otvori .sovpkg datoteku u SOV appu za uvoz paketa." to "Open the .sovpkg file in the SOV app to import the package.",
    "Otvori tablicu" to "Open sheet",
    "Preporučeno za track." to "Recommended for tracking.",
    "Očisti Moju bazu?" to "Clear My Base?",
    "Očisti kartu" to "Clear map",
    "Očisti kartu?" to "Clear map?",
    "Očisti moju bazu" to "Clear My Base",
    "Podijeli SOV izlet" to "Share SOV trip",
    "Podijeli točku s grupom" to "Share point with group",
    "Podijeli track s grupom" to "Share track with group",
    "Područje je spremno. Točke se prikazuju odmah kada otvoriš izlet." to "The area is ready. Points appear as soon as you open the trip.",
    "Preskoči i nastavi" to "Skip and continue",
    "Prijava nije uspjela" to "RSVP failed",
    "Prijava spremljena" to "RSVP saved",
    "Prikaži arhivu — bez vremenske prognoze" to "Show archive — no weather forecast",
    "Prikaži fino podešavanje" to "Show fine tuning",
    "Prikaži prošle izlete" to "Show past trips",
    "Prikaži sve" to "Show all",
    "Primjećene ugroze objekta" to "Observed threats to the cave",
    "Probaj širi pojam, drugu lokaciju ili očisti dio filtera." to "Try a broader term, another location or clear some filters.",
    "Promašen anchor!" to "Missed anchor!",
    "Prozirnost" to "Opacity",
    "Proširi" to "Expand",
    "Prošli izleti su spremljeni dolje u sklopljenoj arhivi." to "Past trips are kept below in the collapsed archive.",
    "Odaberi izvor rezultata." to "Choose result source.",
    "Prvo učitaj GPS poziciju ili zadrži prst na karti" to "First load GPS position or long-press the map",
    "Puno rezultata. Dodaj filter." to "Many results. Add filter.",
    "Reljef / hillshade" to "Relief / hillshade",
    "Ručno odaberi" to "Choose manually",
    "SOV izlet uvezen" to "SOV trip imported",
    "Sakrij arhivu prošlih izleta" to "Hide past-trip archive",
    "Sakrij fino podešavanje" to "Hide fine tuning",
    "Sakrij prošle izlete" to "Hide past trips",
    "Sakrij sve" to "Hide all",
    "Score spremljen." to "Score saved locally; leaderboard will refresh when available.",
    "Pretraga se učitava." to "The search index is warming up in the background. Map and core features remain available.",
    "Search izvor" to "Search source",
    "Search je čist: prvo pojam, pa filteri" to "Search is clean: query first, filters second",
    "Boja znači aktivno." to "Grey = off. Color + checkmark = on and updates results immediately.",
    "Sloj" to "Layer",
    "Sloj je spreman za prikaz na karti i u OFFLINE tabu." to "Layer is ready for the map and the OFFLINE tab.",
    "Slojevi karte" to "Map layers",
    "Spreman za špilju i vertikalu?" to "Ready for cave and vertical sections?",
    "Spremno za teren" to "Ready for fieldwork",
    "Stari track spremljen u Offline" to "Old track saved to Offline",
    "Status" to "Status",
    "Status mreže" to "Network status",
    "Status mreže i vidljive ćelije" to "Network status and visible cells",
    "Stranica" to "Page",
    "Svi overlayi su ugašeni. Ništa nije obrisano." to "All overlays are hidden. Nothing was deleted.",
    "TOP ŠIŠMIŠI" to "TOP BATS",
    "Tamno plave točke" to "Dark-blue points",
    "Tap za cijeli ekran" to "Tap for fullscreen",
    "Teren zadaci" to "Field tasks",
    "Pretvori koordinate." to "Convert coordinates.",
    "Tip objekta" to "Object type",
    "Top šišmiši" to "Top bats",
    "TopoDroid viewer" to "TopoDroid viewer",
    "Točka ažurirana" to "Point updated",
    "Točka spremljena" to "Point saved",
    "Točke iz Moje baze" to "My Base points",
    "Track obrisan" to "Track deleted",
    "Track spremljen" to "Track saved",
    "Traži" to "Search",
    "Traži naziv, lokaciju ili broj pločice" to "Search name, location or tile number",
    "Tražim GPS lokaciju…" to "Looking for GPS location…",
    "Treba dozvola za točan GPS" to "Precise GPS permission is required",
    "UKLJUČENO" to "ON",
    "Udaljenost" to "Distance",
    "Ugrađeni" to "Built-in",
    "GPS pomaže udaljenosti." to "Distance filter is enabled. GPS will help make results more accurate.",
    "Uključeno" to "On",
    "Uključi kartu" to "Enable map",
    "Ukopčaj se" to "Clip in",
    "Ukopčan — spuštanje" to "Clipped in — descent",
    "Ulaz iz šume" to "Forest entrance",
    "Upali GPS" to "Turn on GPS",
    "Upiši HTRS X / Easting." to "Enter HTRS X / Easting.",
    "Upiši HTRS Y / Northing." to "Enter HTRS Y / Northing.",
    "Upiši UTM Easting." to "Enter UTM Easting.",
    "Upiši UTM Northing." to "Enter UTM Northing.",
    "Upiši UTM zonu, npr. 33 ili 34." to "Enter UTM zone, e.g. 33 or 34.",
    "Upiši Web Mercator X." to "Enter Web Mercator X.",
    "Upiši Web Mercator Y." to "Enter Web Mercator Y.",
    "Upiši ime za Speleo Runner leaderboard." to "Enter a name for the Speleo Runner leaderboard.",
    "Upiši latitude / širinu." to "Enter latitude.",
    "Upiši longitude / dužinu." to "Enter longitude.",
    "Upiši pojam i odmah vidi koliko ima rezultata." to "Enter a query and immediately see the result count.",
    "Uredi" to "Edit",
    "Uredi izlet" to "Edit trip",
    "Uvezen je linijski sloj spreman za prikaz na karti." to "Line layer imported and ready for the map.",
    "Uvezen je točkasti sloj spreman za prikaz na karti." to "Point layer imported and ready for the map.",
    "Uvezi KML točke" to "Import KML points",
    "Uvezi KML/CSV točke" to "Import KML/CSV points",
    "Uvezi paket" to "Import package",
    "Uvoz CSV-a nije uspio" to "CSV import failed",
    "Uvoz KML-a nije uspio" to "KML import failed",
    "Uvoz KML/GPX/KMZ/GeoJSON/CSV/XLSX/GPKG/GeoTIFF" to "Import KML/GPX/KMZ/GeoJSON/CSV/XLSX/GPKG/GeoTIFF",
    "Uvoz Moje baze nije uspio" to "My Base import failed",
    "Uvoz SHP/KMZ/ZIP layera" to "Import SHP/KMZ/ZIP layer",
    "Uvoz SOV izleta" to "Import SOV trip",
    "Uvoz prekinut" to "Import cancelled",
    "Uvoz u tijeku" to "Import in progress",
    "Učitavam high scoreove…" to "Loading high scores…",
    "Učitavam…" to "Loading drawing preview…",
    "Učitavam prognozu…" to "Loading forecast…",
    "Uđi u špilju" to "Enter the cave",
    "Velike datoteke učitavaju se u pozadini bez blokiranja karte." to "Large files load in the background without blocking the map.",
    "Već imaš zadnju verziju" to "You already have the latest version",
    "Viewer" to "Viewer",
    "Više..." to "More...",
    "Voditelj" to "Leader",
    "Vozim" to "I can drive",
    "X koordinata" to "X coordinate",
    "Y koordinata" to "Y coordinate",
    "ZAJEDNIČKI RASPORED" to "SHARED SCHEDULE",
    "Najčešće: 33N / 34N." to "For Croatia the most common zones are 33N and 34N.",
    "Za najbolji paket prvo odaberi područje na karti." to "For the best package, choose the map area first.",
    "Dovoljan je datum i lokacija." to "Date and location are enough.",
    "Za bolji track isključi štednju baterije. " to "For reliable tracking, disable battery optimization for SOV. ",
    "Zajednički raspored" to "Shared schedule",
    "Zajednički sloj" to "Shared layer",
    "Zatvori" to "Close",
    "Zona" to "Zone",
    "Zoom" to "Zoom",
    "bez suženja" to "no narrowing",
    "isključeno" to "off",
    "jame + špilje" to "pits + caves",
    "jačina nije dostupna" to "strength unavailable",
    "jačina signala" to "signal strength",
    "npr. Darko / SOV / ekipa" to "e.g. Darko / SOV / team",
    "npr. Gospić, Karlovac, Zadar…" to "e.g. Gospić, Karlovac, Zadar…",
    "npr. Rožanski kukovi" to "e.g. Rožanski kukovi",
    "npr. Vražja jama, Ogulin, 124" to "e.g. Vražja jama, Ogulin, 124",
    "pločica" to "tiles",
    "pločica/lokacija" to "tile/location",
    "pločica…" to "tiles…",
    "potvrđeno" to "confirmed",
    "samo špilje" to "caves only",
    "službeno" to "official",
    "trenutna mreža" to "current network",
    "Čitam survey.sql i pripremam centerline…" to "Reading survey.sql and preparing centerline…",
    "Članovi istraživanja" to "Survey team members",
    "Što treba" to "What is needed",
    "↺ POKUŠAJ PONOVO" to "↺ TRY AGAIN",
    "▸ Uđi u špilju..." to "▸ Enter the cave...",
    "☁️ Oblačno" to "☁️ Cloudy",
    "⚠️ Visoke oborine — rizik od poplave špilje!" to "⚠️ Heavy rain — cave flooding risk!",
    "⚠️ Značajne oborine — pazi na vodotoke u špilji" to "⚠️ Significant rain — watch cave watercourses",
    "⛈ Grmljavina s tučom" to "⛈ Thunderstorm with hail",
    "✓ Izlet dodan u zajednički raspored." to "✓ Trip added to shared schedule.",
    "✓ Ukopčan — spuštanje" to "✓ Clipped in — descent",
    "❄️ Ledena špilja" to "❄️ Ice cave",
    "🌤 Pretežno vedro" to "🌤 Mostly clear",
    "🌧 Jaka kiša" to "🌧 Heavy rain",
    "🌧 Kiša" to "🌧 Rain",
    "🌨 Snježni pljuskovi" to "🌨 Snow showers",
    "🌱 Aragonitna špilja" to "🌱 Aragonite cave",
    "🌿 Ulaz u špilju" to "🌿 Cave entrance",
    "💧 Mokra špilja" to "💧 Wet cave",
    "🚗 Otvori tablicu prijevoza" to "🚗 Open transport sheet",
    "Autor" to "Author"
)

private fun translateDynamicLabel(value: String): String {
    enStaticLabels[value]?.let { return it }
    val directlyTranslated = when {
        value.endsWith(" objekata") && value.contains(" / ") -> value.replace("objekata", "objects")
        value.endsWith(" točaka") -> value.replace("točaka", "points")
        value.endsWith(" trackova") -> value.replace("trackova", "tracks")
        value.endsWith(" stanica") -> value.replace("stanica", "stations")
        value.endsWith(" šišmiša") -> value.replace("šišmiša", "bats")
        value.startsWith("Datum: ") -> value.replaceFirst("Datum: ", "Date: ")
        value.startsWith("Datum izleta: ") -> value.replaceFirst("Datum izleta: ", "Trip date: ")
        value.startsWith("Voditelj: ") -> value.replaceFirst("Voditelj: ", "Leader: ")
        value.startsWith("Lokacija: ") -> value.replaceFirst("Lokacija: ", "Location: ")
        value.startsWith("Naziv: ") -> value.replaceFirst("Naziv: ", "Name: ")
        value.startsWith("Opis: ") -> value.replaceFirst("Opis: ", "Description: ")
        value.startsWith("Snimljeno: ") -> value.replaceFirst("Snimljeno: ", "Recorded: ")
        value.startsWith("Duljina: ") -> value.replaceFirst("Duljina: ", "Length: ")
        value.startsWith("Početak: ") -> value.replaceFirst("Početak: ", "Start: ")
        value.startsWith("Kraj: ") -> value.replaceFirst("Kraj: ", "End: ")
        value.startsWith("Ažurirano: ") -> value.replaceFirst("Ažurirano: ", "Updated: ")
        value.startsWith("Autor: ") -> value.replaceFirst("Autor: ", "Author: ")
        value.startsWith("Pločica: ") -> value.replaceFirst("Pločica: ", "Tile: ")
        value.startsWith("Županija: ") -> value.replaceFirst("Županija: ", "County: ")
        value.startsWith("Dostupna verzija: ") -> value.replaceFirst("Dostupna verzija: ", "Available version: ")
        value.startsWith("Instalirana verzija: ") -> value.replaceFirst("Instalirana verzija: ", "Installed version: ")
        value.startsWith("Prošli izleti") -> value.replaceFirst("Prošli izleti", "Past trips")
        value.startsWith("Prikazujem prvih") -> value
            .replaceFirst("Prikazujem prvih", "Showing first")
            .replace("rezultata", "results")
            .replace("mjerenja", "measurements")
            .replace("trackova", "tracks")
            .replace("layera", "layers")
        value.startsWith("Nema trackova s imenom") -> value.replaceFirst("Nema trackova s imenom", "No tracks named")
        value.startsWith("Nema mjerenja za stanicu") -> value.replaceFirst("Nema mjerenja za stanicu", "No measurements for station")
        value.startsWith("Aktivno: ") -> value.replaceFirst("Aktivno: ", "Active: ")
        value.startsWith("Format: ") -> value.replaceFirst("Format: ", "Format: ")
        value.startsWith("Prioritet: ") -> value.replaceFirst("Prioritet: ", "Priority: ")
        value.startsWith("Izlet ") -> value.replaceFirst("Izlet ", "Trip ")
        value.startsWith("SOV izlet uvezen: ") -> value.replaceFirst("SOV izlet uvezen: ", "SOV trip imported: ")
        value.startsWith("Otvaram područje izleta: ") -> value.replaceFirst("Otvaram područje izleta: ", "Opening trip area: ")
        value.startsWith("Sloj '") && value.endsWith("' obrisan.") -> value.replaceFirst("Sloj '", "Layer '").replace("' obrisan.", "' deleted.")
        value.startsWith("Otvori ") -> value.replaceFirst("Otvori ", "Open ")
        value.startsWith("Download sve pronađene") -> value.replaceFirst("Download sve pronađene", "Download all found")
        value.startsWith("Download moje custom KML točke") -> value.replaceFirst("Download moje custom KML točke", "Download my custom KML points")
        value.startsWith("Custom točke: ") -> value.replaceFirst("Custom točke: ", "Custom points: ")
        value.startsWith("GPS: ") -> value
        value.startsWith("Točke: ") -> value.replaceFirst("Točke: ", "Points: ")
        value.startsWith("Točke crteža: ") -> value.replaceFirst("Točke crteža: ", "Drawing points: ")
        value.startsWith("Automatski: ") -> value.replaceFirst("Automatski: ", "Automatic: ").replace("trackova u području", "tracks in area")
        value.startsWith("Ručno odabrano: ") -> value.replaceFirst("Ručno odabrano: ", "Manually selected: ")
        value.startsWith("Karta '") -> value.replaceFirst("Karta '", "Map '").replace("' bit će zamijenjena novom verzijom iz paketa.", "' will be replaced with the package version.")
        value.startsWith("Score ") -> value
            .replace("horizontalno", "horizontal")
            .replace("vertikala", "vertical")
            .replace("šišmiši", "bats")
        value.startsWith("#") && value.contains(" šiš.") -> value.replace("šiš.", "bats")
        value.startsWith("App će spremiti očišćeni URL") -> value.replaceFirst("App će spremiti očišćeni URL", "The app will save the cleaned URL")
        else -> null
    }
    return directlyTranslated ?: translateCroatianFragments(value)
}

private val enFragmentReplacements = listOf(
    "Obriši" to "Delete",
    "Očisti" to "Clear",
    "Odustani" to "Cancel",
    "Spremi" to "Save",
    "Uvezi" to "Import",
    "Izvezi" to "Export",
    "Preuzmi" to "Download",
    "Osvježi" to "Refresh",
    "Uredi" to "Edit",
    "Podijeli" to "Share",
    "Prikaži" to "Show",
    "Sakrij" to "Hide",
    "Otvori" to "Open",
    "Zatvori" to "Close",
    "Natrag" to "Back",
    "Nastavi" to "Continue",
    "Potvrdi" to "Confirm",
    "Prekini" to "Stop",
    "Greška" to "Error",
    "greška" to "error",
    "Učitavam" to "Loading",
    "Uvoz" to "Import",
    "izvoz" to "export",
    "Izvoz" to "Export",
    "nije uspio" to "failed",
    "nije dostupna" to "unavailable",
    "nije dostupno" to "unavailable",
    "nije pronađena" to "not found",
    "nije pronađen" to "not found",
    "Nema" to "No",
    "nema" to "no",
    "točaka" to "points",
    "točke" to "points",
    "točka" to "point",
    "Točke" to "Points",
    "Točka" to "Point",
    "trackova" to "tracks",
    "Trackovi" to "Tracks",
    "track" to "track",
    "objekata" to "objects",
    "objekt" to "object",
    "Objekt" to "Object",
    "pločica" to "tiles",
    "Pločica" to "Tile",
    "mjerenja" to "measurements",
    "stanica" to "stations",
    "šišmiša" to "bats",
    "špilja" to "cave",
    "Špilja" to "Cave",
    "jame" to "pits",
    "Jame" to "Pits",
    "izlet" to "trip",
    "Izlet" to "Trip",
    "izleti" to "trips",
    "Izleti" to "Trips",
    "zajednički" to "shared",
    "Zajednički" to "Shared",
    "zajednička" to "shared",
    "Zajednička" to "Shared",
    "raspored" to "schedule",
    "Raspored" to "Schedule",
    "Karta" to "Map",
    "karta" to "map",
    "sloj" to "layer",
    "Sloj" to "Layer",
    "slojevi" to "layers",
    "Slojevi" to "Layers",
    "Moja baza" to "My Base",
    "moje baze" to "My Base",
    "Moje baze" to "My Base",
    "osnovna" to "base",
    "Osnovna" to "Base",
    "područje" to "area",
    "Područje" to "Area",
    "lokacija" to "location",
    "Lokacija" to "Location",
    "Datum" to "Date",
    "datum" to "date",
    "Voditelj" to "Leader",
    "voditelj" to "leader",
    "Opis" to "Description",
    "opis" to "description",
    "Naziv" to "Name",
    "naziv" to "name",
    "Napomena" to "Note",
    "napomena" to "note",
    "Koordinate" to "Coordinates",
    "koordinate" to "coordinates",
    "Fotografije" to "Photos",
    "fotografije" to "photos",
    "Nacrti" to "Drawings",
    "nacrti" to "drawings",
    "Kompas" to "Compass",
    "kompas" to "compass",
    "Signal" to "Signal",
    "signal" to "signal",
    "Postavke" to "Settings",
    "postavke" to "settings",
    "Pretraga" to "Search",
    "pretraga" to "search",
    "Rezultati" to "Results",
    "rezultati" to "results",
    "udaljenost" to "distance",
    "Udaljenost" to "Distance",
    "Dubina" to "Depth",
    "dubina" to "depth",
    "Duljina" to "Length",
    "duljina" to "length",
    "Uspon" to "Ascent",
    "Silazak" to "Descent",
    "Snimljeno" to "Recorded",
    "Početak" to "Start",
    "Kraj" to "End",
    "Ažurirano" to "Updated",
    "Autor" to "Author",
    "u tijeku" to "in progress",
    "u pozadini" to "in background",
    "spremno" to "ready",
    "Spremno" to "Ready",
    "spremljeno" to "saved",
    "Spremljeno" to "Saved",
    "obrisan" to "deleted",
    "obrisana" to "deleted",
    "uklonjen" to "removed",
    "uklonjena" to "removed",
    "uključeno" to "on",
    "Uključeno" to "On",
    "isključeno" to "off",
    "Isključeno" to "Off",
    "dozvola" to "permission",
    "Dozvola" to "Permission",
    "internet" to "internet",
    "provjeri" to "check",
    "Provjeri" to "Check",
    "mobitel" to "phone",
    "terenu" to "field",
    "teren" to "field",
    "Terenski" to "Field",
    "članovi" to "members",
    "Članovi" to "Members",
    "ugroze" to "threats",
    "cilj" to "goal",
    "Cilj" to "Goal",
    "prognozu" to "forecast",
    "bit će" to "will be",
    "će biti" to "will be",
    "trajno" to "permanently",
    "obrisani" to "deleted",
    "obrisano" to "deleted",
    "uklonjen" to "removed",
    "uklonjeni" to "removed",
    "lokalnog popisa" to "local list",
    "lokalni paket" to "local package",
    "Mojih izleta" to "My trips",
    "zajedničke tablice" to "shared sheet",
    "zajedničkom rasporedu" to "shared schedule",
    "nije još" to "not yet",
    "Provjeri internet" to "Check your internet",
    "pokušaj opet" to "try again",
    "osvježi popis" to "refresh the list",
    "dodatnog reljefa" to "extra relief",
    "preko karte" to "over the map",
    "nema geo layer" to "no geo layer",
    "nema geo sloja" to "no geo layer",
    "ostaju iznad" to "stay above",
    "prazno ako servis ne traži stil" to "leave empty if the service does not require a style",
    "Uključi" to "Enable",
    "Isključen" to "Off",
    "Uključen" to "On",
    "Čitko" to "Readable",
    "Teren" to "Terrain",
    "Savjet" to "Tip",
    "Preporuka" to "Recommendation",
    "Dodatni servisi" to "Additional services",
    "Dodatni" to "Additional",
    "osnovna karta" to "base map",
    "transparentnost" to "transparency",
    "ručno" to "manually",
    "Ručno" to "Manual",
    "servis" to "service",
    "layera" to "layers",
    "layer" to "layer",
    "layere" to "layers",
    "GetCapabilities" to "GetCapabilities",
    "Učitaj" to "Load",
    "očišćen" to "cleaned",
    "očišćeni" to "cleaned",
    "zahtjeve" to "requests",
    "mora početi" to "must start",
    "Tapni" to "Tap",
    "kut" to "corner",
    "prvi" to "first",
    "drugi" to "second",
    "odabran" to "selected",
    "odabrano" to "selected",
    "detaljnost" to "detail level",
    "download" to "download",
    "downloada" to "download",
    "mjerenje" to "measurement",
    "udaljenosti" to "distance",
    "Crtanje" to "Drawing",
    "crteža" to "drawing",
    "crtež" to "drawing",
    "privremene" to "temporary",
    "privremeni" to "temporary",
    "sadržaj" to "content",
    "navigaciju" to "navigation",
    "navigacija" to "navigation",
    "preciznost" to "accuracy",
    "najbliže" to "nearest",
    "Najbliži" to "Nearest",
    "oko tebe" to "around you",
    "čekam fix" to "waiting for fix",
    "Čekam GPS fix…" to "Waiting for GPS fix…",
    "GPS preciznost" to "GPS accuracy",
    "Dodirni" to "Tap",
    "približavanje" to "zoom in",
    "Početak crteža" to "Drawing start",
    "Zadnja" to "Last",
    "u sklopljenoj arhivi" to "in the collapsed archive",
    "budućih" to "upcoming",
    "prošlih" to "past",
    "Prošli" to "Past",
    "buduće" to "upcoming",
    "završeno" to "finished",
    "završi" to "finish",
    "obavezno" to "required",
    "opcionalno" to "optional",
    "po želji" to "optional",
    "offline karta" to "offline map",
    "Offline karta" to "Offline map",
    "offline karte" to "offline maps",
    "karte" to "maps",
    "Karte" to "Maps",
    "podaci" to "data",
    "Podaci" to "Data",
    "dijeljenje" to "sharing",
    "Dijeljenje" to "Sharing",
    "paket" to "package",
    "Paket" to "Package",
    "terenski" to "field",
    "Terenski" to "Field",
    "članarinu" to "membership",
    "Ažuriranje" to "Update",
    "ažuriranja" to "updates",
    "ažuriranje" to "update",
    "Prognoza" to "Forecast"
)

private fun translateCroatianFragments(value: String): String {
    var translated = value
    for ((from, to) in enFragmentReplacements) {
        translated = translated.replace(from, to)
    }
    return translated
}
