#!/usr/bin/env python3
"""Build one transactional SQL file for the v6.1.45av release."""
from __future__ import annotations

import re
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
SOURCES=[
    ROOT/'sql'/'sov_map_fast_feed_v6145av.sql',
    ROOT/'sql'/'sov_submission_review_rpc_v6145av.sql',
    ROOT/'sql'/'sov_runner_leaderboard_security_v6145av.sql',
]
TARGET=ROOT/'sql'/'sov_release_v6145av.sql'

parts=[]
for source in SOURCES:
    text=source.read_text(encoding='utf-8').strip()
    text,n_begin=re.subn(r'(?im)^\s*begin\s*;\s*$', '', text, count=1)
    text,n_commit=re.subn(r'(?im)^\s*commit\s*;\s*$', '', text, count=1)
    if n_begin!=1 or n_commit!=1:
        raise SystemExit(f'{source.name}: expected one BEGIN and one COMMIT wrapper, found begin={n_begin}, commit={n_commit}.')
    parts.append(f'-- BEGIN {source.name}\n{text.strip()}\n-- END {source.name}')

output='''-- SOV web v6.1.45av — consolidated audited database release
-- Generated by tools/build_release_sql.py from the reviewed component SQL.
-- Apply as one transaction; any failure rolls back the complete release.

begin;

'''+('\n\n'.join(parts))+'''\n\ncommit;\n'''

begin_count=len(re.findall(r'(?im)^\s*begin\s*;\s*$',output))
commit_count=len(re.findall(r'(?im)^\s*commit\s*;\s*$',output))
if begin_count!=1 or commit_count!=1:
    raise SystemExit(f'Consolidated SQL must have one transaction wrapper; begin={begin_count}, commit={commit_count}.')

old=TARGET.read_text(encoding='utf-8') if TARGET.exists() else None
if old==output:
    print('Consolidated release SQL already current.')
else:
    TARGET.write_text(output,encoding='utf-8')
    print(f'Wrote {TARGET.relative_to(ROOT)}')
