#!/usr/bin/env python3
"""Build one transactional SQL file for the v6.1.45av release."""
from __future__ import annotations

import re
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
SOURCES=[
    ROOT/'sql'/'sov_map_fast_feed_v6145av.sql',
    ROOT/'sql'/'sov_submission_review_rpc_v6145av.sql',
    ROOT/'sql'/'sov_runner_leaderboard_security_v6145av.sql',
]
TARGET=ROOT/'sql'/'sov_release_v6145av.sql'

parts=[]
for source in SOURCES:
    text=source.read_text(encoding='utf-8').strip()
    text=re.sub(r'^\s*begin\s*;\s*', '', text, count=1, flags=re.I)
    text=re.sub(r'\s*commit\s*;\s*$', '', text, count=1, flags=re.I)
    parts.append(f'-- BEGIN {source.name}\n{text}\n-- END {source.name}')

output='''-- SOV web v6.1.45av — consolidated audited database release
-- Generated by tools/build_release_sql.py from the reviewed component SQL.
-- Apply as one transaction; any failure rolls back the complete release.

begin;

'''+('\n\n'.join(parts))+'''\n\ncommit;\n'''

old=TARGET.read_text(encoding='utf-8') if TARGET.exists() else None
if old==output:
    print('Consolidated release SQL already current.')
else:
    TARGET.write_text(output,encoding='utf-8')
    print(f'Wrote {TARGET.relative_to(ROOT)}')
