-- SOV web v6.1.45av — consolidated audited database release
-- Generated by tools/build_release_sql.py from the reviewed component SQL.
-- Apply as one transaction; any failure rolls back the complete release.

begin;

-- BEGIN sov_map_fast_feed_v6145av.sql
-- SOV v6.1.45av — fast map feed
-- Purpose:
--   * keep Arhivar's detailed worklist semantics separate from the map feed
--   * replace the 6+ second map query with a compact, deterministic feed
--   * preserve approved-member and role checks at the RPC boundary
-- Safety:
--   * the view is not directly exposed to anon/authenticated
--   * the RPCs remain SECURITY DEFINER with explicit auth/role checks

create or replace view public.sov_map_objects_light
with (security_invoker = true)
as
with base as (
  select
    s.source_id as object_id,
    s.source_id,
    coalesce(nullif(o.data ->> 'name',''), s.name) as object_name,
    coalesce(nullif(o.data ->> 'name',''), s.name) as name,
    coalesce(
      nullif(o.data ->> 'plate_number',''),
      nullif(o.data ->> 'plocica',''),
      nullif(o.data ->> 'pločica',''),
      nullif(st.plate_number,''),
      nullif(s.plate_number,''),
      nullif(s.cadastral_number,'')
    ) as plate_number,
    coalesce(
      nullif(o.data ->> 'plate_number',''),
      nullif(o.data ->> 'plocica',''),
      nullif(o.data ->> 'pločica',''),
      nullif(st.plate_number,''),
      nullif(s.plate_number,''),
      nullif(s.cadastral_number,'')
    ) as cadastral_number,
    coalesce(nullif(o.data ->> 'object_type',''), s.object_type_final) as object_type,
    coalesce(nullif(o.data ->> 'object_type',''), s.object_type_final) as object_type_final,
    coalesce(nullif(o.data ->> 'nearest_place',''), s.nearest_place, s.locality, s.municipality) as nearest_place,
    s.locality,
    s.county,
    s.municipality,
    coalesce(
      case when (o.data ->> 'lat') ~ '^-?[0-9]+(\.[0-9]+)?$' then (o.data ->> 'lat')::double precision end,
      s.lat
    ) as lat,
    coalesce(
      case when (o.data ->> 'lon') ~ '^-?[0-9]+(\.[0-9]+)?$' then (o.data ->> 'lon')::double precision end,
      s.lon
    ) as lon,
    s.depth_m,
    s.length_m,
    s.cadastre_status,
    s.record_status,
    s.field_tasks,
    s.workflow_raw,
    s.in_cadastre_bool,
    s.digital_survey_status,
    s.bibliography_status,
    s.gps_tracklog,
    s.georef_record,
    st.archive_status,
    st.priority,
    st.last_note,
    st.has_coordinates as status_has_coordinates,
    st.has_drawing as status_has_drawing,
    st.has_record as status_has_record,
    st.has_plate as status_has_plate,
    st.has_photo as status_has_photo,
    st.needs_redraw as status_needs_redraw,
    st.has_katastar_ready as status_katastar_ready,
    coalesce(st.workflow_checks, '{}'::jsonb) as workflow_checks,
    coalesce(
      nullif(o.data ->> 'access_description',''),
      nullif(o.data ->> 'pristup',''),
      nullif(s.raw ->> 'access_description',''),
      nullif(s.raw ->> 'pristup','')
    ) as access_description,
    coalesce(
      nullif(o.data ->> 'technical_description',''),
      nullif(o.data ->> 'description',''),
      nullif(o.data ->> 'opis',''),
      nullif(s.raw ->> 'technical_description',''),
      nullif(s.raw ->> 'description',''),
      nullif(s.raw ->> 'opis','')
    ) as technical_description,
    greatest(s.updated_at, o.updated_at, st.updated_at) as updated_at,
    public.sov_txt_norm(concat_ws(' ',
      s.cadastre_status, s.record_status, s.field_tasks, s.workflow_raw,
      s.digital_survey_status, s.bibliography_status, s.gps_tracklog,
      s.georef_record, st.last_note
    )) as status_text_norm
  from public.speleo_objects_staging s
  left join public.speleo_object_overrides o on o.object_id = s.source_id
  left join public.sov_archive_object_status st on st.object_id = s.source_id
), flags as (
  select
    b.*,
    (
      b.status_text_norm like '%nije u katastru%'
      or b.status_text_norm like '%nije_u_katastru%'
      or b.status_text_norm like '%ne nalazi se u katastru%'
      or b.status_text_norm like '%nije objekt u katastru%'
    ) as explicit_not_in_cadastre,
    (
      b.status_text_norm ~ '((fali|nedostaje|nema|bez|treba|potrebno|ponoviti|srediti|dopuniti).{0,80}(koordinat|gps|wgs|htrs|lokacij|pozicij|georef))'
      or b.status_text_norm ~ '((koordinat|gps|wgs|htrs|lokacij|pozicij|georef).{0,80}(fali|nedostaje|nema|bez|treba|potrebno|ponoviti|srediti|dopuniti))'
    ) as explicit_missing_coordinates,
    (
      b.status_text_norm ~ '((fali|nedostaje|nema|bez|treba|potrebno|ponoviti|srediti|digitalizirati|napraviti).{0,80}(nacrt|tlocrt|profil|poligon|crtez|crtanje|topodroid))'
      or b.status_text_norm ~ '((nacrt|tlocrt|profil|poligon|crtez|crtanje|topodroid).{0,80}(fali|nedostaje|nema|bez|treba|potrebno|ponoviti|srediti|digitalizirati|napraviti))'
    ) as explicit_missing_drawing,
    (
      b.status_text_norm ~ '((fali|nedostaje|nema|bez|treba|potrebno|srediti|napraviti|dopuniti).{0,80}(zapisnik|tzapisnik|izvjestaj|bibliograf))'
      or b.status_text_norm ~ '((zapisnik|tzapisnik|izvjestaj|bibliograf).{0,80}(fali|nedostaje|nema|bez|treba|potrebno|srediti|napraviti|dopuniti))'
    ) as explicit_missing_record,
    (
      b.status_text_norm ~ '((fali|nedostaje|nema|bez|treba|potrebno|postaviti|dodati|upisati).{0,80}(plocic|broj plocice|oznaka))'
      or b.status_text_norm ~ '((plocic|broj plocice|oznaka).{0,80}(fali|nedostaje|nema|bez|treba|potrebno|postaviti|dodati|upisati))'
    ) as explicit_missing_plate,
    (
      b.status_text_norm ~ '((fali|nedostaje|nema|bez|treba|potrebno|napraviti|dodati).{0,80}(fotka|foto|slika|fotograf))'
      or b.status_text_norm ~ '((fotka|foto|slika|fotograf).{0,80}(fali|nedostaje|nema|bez|treba|potrebno|napraviti|dodati))'
    ) as explicit_missing_photo,
    (
      b.status_text_norm ~ '(ponoviti_nacrt|nacrt_ponoviti|ponoviti.{0,40}nacrt|ponovno.{0,40}nacrt)'
    ) as explicit_needs_redraw
  from base b
), effective as (
  select
    f.*,
    (
      not f.explicit_not_in_cadastre
      and (
        coalesce(f.in_cadastre_bool,false)
        or public.sov_txt_norm(coalesce(f.cadastre_status,'')) in ('u_katastru','objekt_unesen')
        or public.sov_txt_norm(coalesce(f.record_status,'')) in ('u_katastru','u_katastru_editirati','objekt_unesen')
      )
    ) as base_in_cadastre,
    (
      coalesce(f.status_katastar_ready,false)
      or public.sov_txt_norm(coalesce(f.record_status,'')) = 'za_unos_u_katastar'
      or f.status_text_norm like '%ima podatke za unos u katastar%'
    ) as base_ready_for_katastar,
    coalesce(f.status_has_coordinates,
      case when f.explicit_missing_coordinates then false else f.lat is not null and f.lon is not null end
    ) as has_coordinates,
    coalesce(f.status_has_drawing, not f.explicit_missing_drawing) as has_drawing,
    coalesce(f.status_has_record, not f.explicit_missing_record) as has_record,
    coalesce(f.status_has_plate,
      case when f.explicit_missing_plate then false else coalesce(f.plate_number,'') <> '' end
    ) as has_plate,
    coalesce(f.status_has_photo, not f.explicit_missing_photo) as has_photo,
    coalesce(f.status_needs_redraw, f.explicit_needs_redraw) as needs_redraw
  from flags f
), final as (
  select
    e.*,
    not e.has_coordinates as missing_coordinates,
    not e.has_drawing as missing_drawing,
    not e.has_record as missing_record,
    not e.has_plate as missing_plate,
    not e.has_photo as missing_photo,
    array_remove(array[
      case when not e.has_plate then 'pločica' end,
      case when not e.has_coordinates then 'koordinate' end,
      case when not e.has_drawing then 'nacrt' end,
      case when not e.has_record then 'zapisnik' end,
      case when not e.has_photo then 'fotka' end,
      case when e.needs_redraw then 'ponoviti nacrt' end
    ], null) as missing_categories
  from effective e
)
select
  object_id,
  source_id,
  object_name,
  name,
  plate_number,
  cadastral_number,
  object_type,
  object_type_final,
  nearest_place,
  locality,
  county,
  municipality,
  lat,
  lon,
  depth_m,
  length_m,
  cadastre_status,
  record_status,
  field_tasks,
  workflow_raw,
  in_cadastre_bool,
  archive_status,
  priority,
  last_note,
  workflow_checks,
  access_description,
  technical_description,
  base_in_cadastre,
  base_ready_for_katastar,
  has_coordinates,
  has_drawing,
  has_record,
  has_plate,
  has_photo,
  needs_redraw,
  missing_coordinates,
  missing_drawing,
  missing_record,
  missing_plate,
  missing_photo,
  missing_categories,
  array_to_string(missing_categories, ', ') as missing_categories_text,
  case
    when base_in_cadastre then 'u_katastru'
    when base_ready_for_katastar then 'spremno_za_katastar'
    when explicit_not_in_cadastre then 'nije_u_katastru_provjeriti'
    when cardinality(missing_categories) > 0 then 'nepotpuno'
    else 'provjeriti'
  end as katastar_readiness,
  (
    case when missing_coordinates then 30 else 0 end
    + case when missing_drawing then 25 else 0 end
    + case when missing_record then 25 else 0 end
    + case when missing_plate then 15 else 0 end
    + case when missing_photo then 8 else 0 end
    + case when needs_redraw then 12 else 0 end
    + case when coalesce(priority,'normal') = 'high' then 20 else 0 end
    + case when base_ready_for_katastar then 10 else 0 end
  ) as priority_score,
  lower(concat_ws(' ',
    object_name, plate_number, nearest_place, locality, municipality, county,
    object_type, cadastre_status, record_status, field_tasks, workflow_raw,
    array_to_string(missing_categories, ' ')
  )) as search_text,
  updated_at
from final;

revoke all on public.sov_map_objects_light from public;
revoke all on public.sov_map_objects_light from anon;
revoke all on public.sov_map_objects_light from authenticated;

drop function if exists public.sov_map_objects(integer);
create function public.sov_map_objects(p_limit integer default 20000)
returns table(data jsonb)
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $function$
declare
  lim integer := greatest(1, least(coalesce(p_limit, 20000), 50000));
begin
  if auth.uid() is null then
    raise exception 'Nisi prijavljen.' using errcode = '42501';
  end if;
  if not (
    public.sov_rls_is_active_member(auth.uid())
    or public.sov_rls_has_any_role(array['admin','arhivar','webmaster']::text[], auth.uid())
  ) then
    raise exception 'Nemaš pristup karti/bazi objekata.' using errcode = '42501';
  end if;

  return query
  select to_jsonb(t)
  from (
    select *
    from public.sov_map_objects_light
    order by priority_score desc nulls last, object_name asc nulls last
    limit lim
  ) t;
end;
$function$;

drop function if exists public.sov_map_objects_page(integer, integer);
create function public.sov_map_objects_page(p_offset integer default 0, p_limit integer default 1000)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $function$
declare
  off integer := greatest(0, coalesce(p_offset, 0));
  lim integer := greatest(1, least(coalesce(p_limit, 1000), 1000));
  rows jsonb := '[]'::jsonb;
begin
  if auth.uid() is null then
    raise exception 'Nisi prijavljen.' using errcode = '42501';
  end if;
  if not (
    public.sov_rls_is_active_member(auth.uid())
    or public.sov_rls_has_any_role(array['admin','arhivar','webmaster']::text[], auth.uid())
  ) then
    raise exception 'Nemaš pristup karti/bazi objekata.' using errcode = '42501';
  end if;

  select coalesce(jsonb_agg(to_jsonb(t) order by t.priority_score desc nulls last, t.object_name asc nulls last), '[]'::jsonb)
  into rows
  from (
    select *
    from public.sov_map_objects_light
    order by priority_score desc nulls last, object_name asc nulls last
    offset off
    limit lim
  ) t;

  return jsonb_build_object(
    'source', 'sov_map_objects_light',
    'offset', off,
    'limit', lim,
    'rows', rows,
    'count', jsonb_array_length(rows)
  );
end;
$function$;

revoke all on function public.sov_map_objects(integer) from public;
revoke all on function public.sov_map_objects(integer) from anon;
grant execute on function public.sov_map_objects(integer) to authenticated;
grant execute on function public.sov_map_objects(integer) to service_role;

revoke all on function public.sov_map_objects_page(integer, integer) from public;
revoke all on function public.sov_map_objects_page(integer, integer) from anon;
grant execute on function public.sov_map_objects_page(integer, integer) to authenticated;
grant execute on function public.sov_map_objects_page(integer, integer) to service_role;

comment on view public.sov_map_objects_light is
  'Compact map feed separated from the expensive Arhivar worklist. Direct access is revoked; use map RPCs.';
comment on function public.sov_map_objects(integer) is
  'Approved-member map feed using sov_map_objects_light.';
comment on function public.sov_map_objects_page(integer, integer) is
  'Paged approved-member map feed using sov_map_objects_light.';
-- END sov_map_fast_feed_v6145av.sql

-- BEGIN sov_submission_review_rpc_v6145av.sql
-- SOV v6.1.45av — stable Arhivar submission review endpoint
-- Removes the permanent 404/fallback path used by arhivar-submissions-review.js.
-- Aligns database reviewer roles with auth.js: webmaster, admin and arhivar.

create or replace function public.sov_submissions_is_reviewer()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public, auth
as $function$
  select public.sov_submission_current_role_safe() in ('webmaster','admin','arhivar')
     and public.sov_submission_current_status_safe() in ('approved','active','enabled','ok');
$function$;

revoke all on function public.sov_submissions_is_reviewer() from public;
revoke all on function public.sov_submissions_is_reviewer() from anon;
grant execute on function public.sov_submissions_is_reviewer() to authenticated;
grant execute on function public.sov_submissions_is_reviewer() to service_role;

create or replace function public.sov_update_speleo_submission_review(
  p_submission_id uuid,
  p_status text,
  p_missing_categories text[] default '{}'::text[],
  p_archivist_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $function$
declare
  v_status text := lower(trim(coalesce(p_status,'')));
  v_count integer := 0;
begin
  if auth.uid() is null then
    raise exception 'Nisi prijavljen.' using errcode = '42501';
  end if;
  if not public.sov_submissions_is_reviewer() then
    raise exception 'Samo webmaster/admin/arhivar može ažurirati review predaje.' using errcode = '42501';
  end if;
  if v_status not in ('submitted','needs_changes','approved','rejected') then
    raise exception 'Nepodržan status predaje: %', p_status using errcode = '22023';
  end if;

  update public.speleo_object_submissions
  set status = v_status,
      missing_categories = coalesce(p_missing_categories, '{}'::text[]),
      archivist_note = p_archivist_note,
      reviewed_by = auth.uid(),
      reviewed_at = now(),
      updated_at = now()
  where id = p_submission_id;

  get diagnostics v_count = row_count;
  if v_count = 0 then
    raise exception 'Predaja ne postoji.' using errcode = 'P0002';
  end if;

  return jsonb_build_object(
    'ok', true,
    'submission_id', p_submission_id,
    'status', v_status,
    'missing_categories', coalesce(p_missing_categories, '{}'::text[])
  );
end;
$function$;

revoke all on function public.sov_update_speleo_submission_review(uuid,text,text[],text) from public;
revoke all on function public.sov_update_speleo_submission_review(uuid,text,text[],text) from anon;
grant execute on function public.sov_update_speleo_submission_review(uuid,text,text[],text) to authenticated;
grant execute on function public.sov_update_speleo_submission_review(uuid,text,text[],text) to service_role;

comment on function public.sov_submissions_is_reviewer() is
  'True for approved webmaster/admin/arhivar users; aligned with web auth archive permission.';
comment on function public.sov_update_speleo_submission_review(uuid,text,text[],text) is
  'Reviewer-only endpoint for submitted/needs_changes/approved/rejected workflow updates.';
-- END sov_submission_review_rpc_v6145av.sql

-- BEGIN sov_runner_leaderboard_security_v6145av.sql
-- SOV v6.1.45av — Spelo Runner leaderboard security hardening
-- Keep public high-score reads while removing view-owner privilege bypass and
-- unnecessary anonymous write grants.

create or replace view public.sov_runner_leaderboard
with (security_invoker = true)
as
select
  player_name as name,
  score,
  bats,
  date_text,
  source,
  played_at,
  created_at
from public.sov_runner_scores
where score > 0
  and bats >= 0
  and length(player_name) between 1 and 80;

revoke all on public.sov_runner_leaderboard from public;
revoke all on public.sov_runner_leaderboard from anon;
revoke all on public.sov_runner_leaderboard from authenticated;
grant select on public.sov_runner_leaderboard to anon, authenticated, service_role;

-- Public users only need leaderboard reads. Authenticated staff retain table
-- DML grants, with the existing staff RLS policy deciding who may write.
revoke insert, update, delete, truncate, references, trigger
  on public.sov_runner_scores from anon;
grant select on public.sov_runner_scores to anon;

comment on view public.sov_runner_leaderboard is
  'Public Spelo Runner leaderboard; security_invoker enforces sov_runner_scores RLS.';
-- END sov_runner_leaderboard_security_v6145av.sql

commit;
